components/blockchain-grid.tsx

This PR introduces a **Blockchain Grid Visualization** component using **React, Tailwind CSS, and GSAP animations**. It simulates a dynamic blockchain network with:  
✅ **Animated grid blocks** appearing sequentially.  
✅ **Continuous data flow animations** representing transactions.  
✅ **Pulsing and glowing effects** for selected blocks.  
✅ **Floating particles** for an interactive feel.  
✔ **Grid Structure**  
- Created a **10x6 grid** to represent blockchain blocks.  
- Each block is styled with a semi-transparent background and border effects.  
✔ **GSAP Animations**  
- **Block appearance animation:** Blocks appear with a staggered scale-up effect.  
- **Data flow animation:** Continuous moving horizontal and vertical lines simulate transactions.  
- **Pulsing block effects:** …

# Blockchain Grid Visualization with GSAP Animations 🚀  

---

components/navbar.tsx

feat: implemented navBar

---

components/auth/sign-in-form.tsx

implementation of sign in form and it's appropriate logic
close: issue#6

sign in form

---

components/stars-animation.tsx
components/stars-background.tsx

Added StarsField component with dynamic animation effects

Added StarsField component with dynamic animation effects

---

components/globe.tsx

Description
This PR introduces a fully interactive 3D globe visualization component built with @react-three/fiber and Three.js. The component features a realistic Earth globe with atmospheric effects, 8 dynamic space objects (asteroids, satellites, comets, planets) with physics-based movement, and a starfield background with 4,000 twinkling stars. It includes smooth orbital controls, automatic rotation, and performance optimizations to ensure 60 FPS across devices. The implementation is responsive, accessibility-compliant (WCAG 2.1 AA), and includes comprehensive documentation. Closes #26 
Changes Made
Core Component (globe.tsx):
Created a reusable React component using @react-three/fiber for rendering the 3D scene.
Integrated Three.js for globe geometry, texture mapping (4K Earth …

added globe component

---

components/crypto-table.tsx

created the crypto table component

Crypto table

---

components/ui/multilingual-welcome.tsx
lib/localization-utils.ts
lib/mock-data.ts
lib/text-animations.ts

Overview
This PR introduces multilingual support for our welcome messages and related UI components by extending our localization data model. The updates focus on enhancing support for right-to-left (RTL) languages and script type identification, ensuring that the UI can correctly render content based on language-specific needs.
Key Changes
Extended Data Model:
The base welcome message type has been extended to support optional properties for RTL layouts and script types. This enhancement allows for a more nuanced handling of languages that require special rendering considerations.
Updated Component Props:
The component responsible for displaying welcome messages now accepts an array of these extended messages. This change ensures that any additional localization data, such as RTL and …

implement the multilingual welcome message

---

components/animated-background.tsx
lib/footer-animations.ts

The footer Animated Background was successfully created and implemented which was able to be displayed in the footer background.

Background-Animation-Created

---

components/auth/reset-passkey-form.tsx
components/wallet-button.tsx
package-lock.json
package.json
tsconfig.json

fix: resolve issues in wallet button and reset passkey form
refactor: improve wallet button functionality and reset passkey form
style: enhance UI for wallet button and reset passkey form

I created wallet button and the reset passkeyform

---

app/not-found.tsx

This PR introduces a custom 404 Not Found page to enhance the user experience when navigating to invalid routes.
closes #16 
- Created a `not-found.tsx` page inside the app directory.
- Styled the page using Tailwind CSS for a clean and modern UI.
- Added a Go Back to Home button for easy navigation.
- Responsive design for all screen sizes.
- Centered error message with a minimalistic look.
- Provides a clear call to action for users to return home.

not found page

---

globals.css

This PR preserves and enhances the application-wide styling system in `globals.css` to ensure visual consistency, optimize theme configurations, and maintain smooth cross-browser animations per issue #27.
- Maintained Tailwind CSS layer configuration
- Preserved dark theme CSS custom properties (e.g., `--background: 240 10% 3.9%`, `--foreground: 0 0% 98%`)
- Kept gradient text animation effects and existing keyframes
- Ensured smooth color scheme transitions with `prefers-color-scheme` media queries
- Upheld mobile-first responsive design and animation performance optimizations
- Verified CSS variable compatibility across components
- Documented theme variables and animations in `globals.css`
- Confirmed consistent styling across all components
- Tested animations and transitions in major …

Added and Maintained Global Style Issue #27

---

app/news/layout.tsx
app/news/page.tsx
tsconfig.json

Changes made
- Created `layout.tsx` for shared structure
- Added `page.tsx` for news content
- Followed Next.js 13+ conventions

Added News page and Layout component under `app/news/`.

---

app/layout.tsx
components/animated-background.tsx
components/button-group.tsx
package-lock.json
package.json
tsconfig.json

Resolved critical SSR compatibility issues and improved project configuration:
- Fixed TypeScript import path resolution for component modules
- Added SSR-safe dynamic loading for Three.js-based components
- Updated Next.js configuration for proper alias resolution
- Addressed React hooks compatibility in Server Components
- Added Browserslist maintenance script
- Eliminates server-side rendering errors in layout components
- Ensures proper Three.js canvas initialization
- Improves long-term dependency maintenance
- Maintains client/server component boundaries
Run `npm run update-db` periodically to keep browser compatibility data fresh

chores: fixed broken app and home components

---

components/sidebar.tsx

Closes #60  Implement a new Sidebar component with collapsible/expandable behavior.”
Please review the implementation details and let me know if any tweaks are needed!

Sidebar created

---

components/wallet-connect-model.tsx

Closed: #61 
This PR introduces a new `WalletConnectModal` component that enables users to connect their **Argent X wallet** via the `starknet-react` library. Key features and improvements include:
- **Modal-based Wallet Connection UI** using `createPortal` for rendering.
- **Argent X detection and connection** via `@starknet-react/core` connector lookup.
- Visual **feedback for connecting state**, including loading spinner.
- **Graceful error handling** and display if connection fails or wallet is not found.
- Automatic callback on successful connection via `onConnectSuccess`.
- Styled with TailwindCSS using a **dark glassmorphic UI**, consistent with the app’s aesthetic.
- Links to **install Argent X** if not already installed.

feat: add WalletConnectModal with Argent X support using starknet-react

---

components/wallet-button.tsx

Related Issue: #66
This PR introduces a visually striking cosmic-themed Wallet Button component that serves as the primary entry point for wallet connections in StarkPulse. The implementation includes stellar animations, gradient borders, and responsive interactions while maintaining full compatibility with both client-side and server-side rendering.
✅ Cosmic Visual Design
- Animated star particle system with orbital glow effects
- Multi-color gradient borders with primary brand highlights
- Smooth CSS-powered animations (60fps optimized)
✅ Enhanced Interactivity
- Responsive hover/active states with luminosity effects
- Customizable button text via children prop
-Wallet icon integration using Lucide
✅ Technical Implementation
- Built with React + TypeScript using "use client" directive
- …

Implement Cosmic-Themed Wallet Button Component

---

app/dashboard/page.tsx

The new Dashboard page was implemented using React + TypeScript. All core componentswere fully integrated. 
The interface is dark-themed, responsive, and maintains the desired UI/UX.  Data is displayed clearly and formatted correctly. All design and functionality requirements met .

Dashboard Page Implementation for StarkPulse #55

---

.gitignore
README.md
src/config/index.ts

- Add config loader with schema validation and type safety
- Update .gitignore to exclude all .env files except .env.example
- Document environment setup and variables in README.md 
closes #81

feat(config): implement robust environment configuration system

---

data-processing/requirements.txt
data-processing/src/schedulers/task_scheduler.py
data-processing/src/services/email_service.py
data-processing/src/services/export_service.py
data-processing/src/services/reporting_service.py

I'm done with the code/ All technical requirement done

Addign Service, Export, email service, reporting file

---

data-processing/docs/unified_api_client.md
data-processing/examples/api_client_usage.py
data-processing/src/config/settings.py
data-processing/src/services/api_client.py
data-processing/tests/unit/test_unified_api_client.py

This PR introduces a comprehensive unified API client service for external data sources, fulfilling the requirements of the assigned issue. The new client provides:
- **HTTP client with retry mechanisms** (exponential backoff)
- **Sliding window rate limiting**
- **Response caching** (Redis-backed)
- **Comprehensive error handling and logging**
- **Unified interface and specialized clients** for CoinMarketCap, NewsAPI, and CoinGecko
---
- `src/services/api_client.py`: New unified API client implementation
- `src/config/settings.py`: Added config options for cache, rate limiting, and retry logic
- `tests/unit/test_unified_api_client.py`: Comprehensive unit tests for all features
- `examples/api_client_usage.py`: Example usage script
- `docs/unified_api_client.md`: Full documentation
--- …

Implement Unified API Client Service with Retry, Rate Limiting, Caching, and Error Handling

---

backend-api/nodemon.json
backend-api/package-lock.json
backend-api/package.json
backend-api/scripts/seed-database.js
backend-api/server.js
backend-api/src/config/index.js
backend-api/src/config/jwt.js
backend-api/src/controllers/authController.js
backend-api/src/controllers/userController.js
backend-api/src/middleware/auth.js
backend-api/src/middleware/errorHandler.js
backend-api/src/middleware/rateLimiter.js
backend-api/src/middleware/validation.js
backend-api/src/models/User.js
backend-api/src/routes/auth.js
backend-api/src/routes/users.js
backend-api/src/services/authService.js
backend-api/src/services/emailService.js
backend-api/src/services/userService.js

Closes #83
This PR implements a complete user management API with Express.js, MongoDB, and JWT-based authentication. The system includes enterprise security features, GDPR compliance, and comprehensive account management.
- **JWT utilities** for token generation/verification
- Bcrypt password hashing (12 rounds)
- Account lockout after 5 failed attempts (2-hour lockout)
- Rate limiting: 100 requests/15min general, 5 auth requests/15min
- Input validation with Joi
- Complete registration/login flow
- Profile updates and password changes
- Email-based password reset with secure tokens
- Account deletion and deactivation options
- GDPR-compliant data export
- Welcome emails, password reset links
- Email verification system
- HTML email templates
- POST /register - User registration with …

User management api

---

data-processing/src/processors/crypto_data_processor.py
data-processing/src/services/api_client.py

Implemented the comprehensive cryptocurrency data processing including price feeds, market data, and historical information ensuring it has the below requirements and all criteria were met:
Multiple API integrations (CoinGecko, CoinMarketCap)
Real-time price updates
Historical data processing
Data validation and normalization
Real-time price data collection
Historical data backfill capability
Data validation and error handling
Rate limiting and API quota management
close[#104 ]

Created the Cryptocurrency data processor

---

apps/backend-api/ENVIRONMENT.md
apps/backend-api/package-lock.json
apps/backend-api/package.json
apps/backend-api/server.js
apps/backend-api/src/config/environment.js
apps/backend-api/src/config/environment.validate.js
apps/backend-api/src/config/jwt.js
apps/backend-api/src/middleware/validation.js
apps/backend-api/src/services/emailService.js

This PR introduces a comprehensive environment configuration system to securely manage application settings across different environments (development, staging, production).
* **Environment Templates**: Added `.env` templates for different environments.
* **Validation Schema**: Validates environment variables on startup using `Joi`.
* **Sensitive Data Protection**: Ensures secrets like DB credentials, JWT keys, and API keys are never logged.
* **Typed Config Object**: Centralized and structured config object (`config/environment.validate.js`) for accessing environment variables with defaults and type safety.
* **Clean Integration**: Replaced direct `process.env` usage with `config` throughout the app (e.g., MongoDB, JWT, email, rate limiters).
* **Documentation**: Added `ENVIRONMENT.md` …

Implement environment config system

---

apps/backend-api/package-lock.json
apps/backend-api/package.json
apps/backend-api/server.js
apps/backend-api/src/middleware/auth.js
apps/backend-api/src/middleware/errorHandler.js
apps/backend-api/src/middleware/rateLimiter.js
apps/backend-api/src/routes/gatewayRoutes.js
apps/backend-api/src/services/proxyService.js
apps/backend-api/src/utils/logger.js

mplement comprehensive error handling and logging system with structured logging, error categorization, monitoring integration, and proper error responses for debugging and monitoring.
close issue : #89

Error Handling and Logging System Feat #89

---

README.md
apps/backend-api/.github/workflows/tests.yml
apps/backend-api/README.md
apps/backend-api/package-lock.json
apps/backend-api/package.json
apps/backend-api/server.js
apps/backend-api/src/controllers/userController.js
apps/backend-api/src/middleware/auth.js
apps/backend-api/src/routes/users.js
apps/backend-api/tests/README.md
apps/backend-api/tests/fixtures/mockData.js
apps/backend-api/tests/integration/auth.test.js
apps/backend-api/tests/integration/users.test.js
apps/backend-api/tests/performance/auth-performance.yml
apps/backend-api/tests/setup.js
apps/backend-api/tests/unit/auth.test.js
apps/backend-api/tests/unit/users.test.js
apps/data-processing/README.md
apps/webapp/README.md

Comprehensive Testing Suite

---

apps/backend-api/server.js
apps/backend-api/src/config/alerts.js
apps/backend-api/src/controllers/alertController.js
apps/backend-api/src/middleware/alertLimiter.js
apps/backend-api/src/models/Alert.js
apps/backend-api/src/models/NotificacatonLog.js
apps/backend-api/src/routes/alert.js
apps/backend-api/src/services/AlertService.js
apps/backend-api/src/services/MonitoringService.js
apps/backend-api/src/services/NotificationService.js
apps/backend-api/src/services/PriceService.js
apps/backend-api/src/utils/websocket.js

I've created a comprehensive price alert system that meets all the technical requirements. Here's what I've implemented:
Core Features:
1. Alert Configuration
Support for multiple alert types: price above/below thresholds and percentage changes
Flexible timeframes (1h, 24h, 7d) for percentage-based alerts
Multiple delivery methods (email, push, WebSocket)
2. Database Models
Alert Model: Stores user alerts with proper indexing for performance
NotificationLog Model: Tracks all notification attempts and their status
3. Services Architecture
PriceService: Handles cryptocurrency price fetching with caching (30s TTL)
AlertService: Manages CRUD operations and alert condition evaluation
NotificationService: Handles multi-channel notification delivery
MonitoringService: Background cron job that …

price alert feature implemented

---

backend-api/package-lock.json
backend-api/package.json
backend-api/server.js
backend-api/src/redisClient.js
backend-api/src/routes/market.js
backend-api/src/routes/news.js
backend-api/src/services/cacheService.js

This PR introduces a comprehensive Redis caching solution for key performance-critical components in the Express.js backend, including:
- Market prices
- News articles
- API responses
- User sessions
- ✅ Integrated Redis using `redis` package
- ✅ Centralized `CacheService` for clean and reusable cache operations (`get`, `set`, `del`, `reset`)
- ✅ Cached frequently accessed routes (`/market/prices`, `/news`)
- ✅ Configurable TTL for each data type (e.g., prices: 1 min, news: 5 min)
- ✅ Redis-powered session store using `express-session` and `connect-redis`
- ✅ Implemented smart cache invalidation on updates to ensure data freshness
- ✅ Enabled cache hit/miss logging for monitoring
- ✅ Ready for horizontal scaling via distributed Redis
- Verified cache hits/misses through logs
- Validated …

 Redis Caching Layer for Express API

---

apps/backend-api/src/controllers/newsController.js
apps/backend-api/src/models/News.js
apps/backend-api/src/routes/news.js
apps/backend-api/src/services/newsService.js
apps/backend-api/src/utils/newsAnalyzer.js
apps/backend-api/tests/news.test.js

News Aaggregation API

---

apps/backend-api/src/models/News.js
apps/backend-api/src/models/Portfolio.js
apps/backend-api/src/models/User.js
apps/backend-api/src/routes/search.js
apps/backend-api/src/routes/v2/index.js
apps/backend-api/src/services/elasticClient.js
apps/backend-api/src/services/search.service.js

Implement advanced search and filtering system
- Adds Elasticsearch integration for news, portfolio, and user data
- Supports full-text search, faceted filtering, auto-complete, and analytics
closes #93

implement advanced search and filtering system

---

apps/data-processing/requirements-dev.txt
apps/data-processing/requirements.txt
apps/data-processing/src/nlp/news_nlp_pipeline.py
apps/data-processing/tests/test_news_nlp_pipeline.py

Advanced NLP Pipeline for Cryptocurrency News Analysis
Overview
A comprehensive, modular NLP pipeline was developed to analyze cryptocurrency news articles, extract insights, and predict market impact using state-of-the-art machine learning and natural language processing techniques. The pipeline is implemented in the NewsNLPPipeline class, located at apps/data-processing/src/nlp/news_nlp_pipeline.py, and is fully tested with a suite in tests/test_news_nlp_pipeline.py.
Key Features
Pre-trained Sentiment Analysis Models
Integrates BERT and FinBERT models via HuggingFace transformers.
Supports model versioning and easy extension for A/B testing.
NLP Preprocessing and Cleaning
Utilizes spaCy for tokenization, lemmatization, and language detection (English and French).
Cleans and normalizes …

implementation og machinr learning power news setiment analysis

---

apps/webapp/app/dashboard/page.tsx
apps/webapp/app/news/page.tsx
apps/webapp/components/navbar.tsx
apps/webapp/package-lock.json
apps/webapp/package.json
apps/webapp/store/auth-store.ts
apps/webapp/store/index.ts
apps/webapp/store/integration-hooks.ts
apps/webapp/store/market-store.ts
apps/webapp/store/news-store.ts
apps/webapp/store/portfolio-store.ts
apps/webapp/store/types.ts
apps/webapp/store/ui-store.ts

Implement Zustand state management

---

apps/backend-api/package-lock.json
apps/backend-api/server.js
apps/backend-api/src/routes/content.js
apps/backend-api/src/routes/governance.js
apps/backend-api/src/routes/validation.js
apps/backend-api/src/routes/validators.js
apps/backend-api/src/services/ConsensusEngine.js
apps/backend-api/src/services/ContentVerification.js
apps/backend-api/src/services/EditorialIndependence.js
apps/backend-api/src/services/ManipulationDetection.js
apps/backend-api/src/services/ReputationSystem.js
apps/backend-api/src/services/ValidationNetwork.js
apps/backend-api/src/services/index.js

Distributed Content Validation Network

---

apps/data-processing/src/streaming/config.py
apps/data-processing/src/streaming/core/stream_manager.py
apps/data-processing/src/streaming/core/websocket_client.py
apps/data-processing/src/streaming/providers/binance_provider.py
apps/data-processing/src/streaming/providers/coingecko_provider.py
apps/data-processing/src/streaming/requirements.txt

Description:
This pull request introduces a robust audit and compliance system designed to meet stringent institutional regulatory requirements. The implementation focuses on ensuring transparency, accountability, and data integrity through comprehensive audit trails, automated regulatory reporting, and real-time compliance monitoring.
closes #168 
Key Features Implemented:
Audit Trail System:
Comprehensive Activity Logging: All system and user activities are now logged to provide a complete operational history.
Immutable Records: Audit logs are immutable and cryptographically verified to prevent tampering and ensure data integrity.
User Action Tracking: Detailed tracking of user actions, including data access and modifications, with clear attribution.
Regulatory Compliance Engine: …

Feat: Implement Comprehensive Audit and Compliance System

---

apps/backend-api/server.js
apps/backend-api/src/compliance/compliance_service.js
apps/backend-api/src/monitoring/index.js
apps/backend-api/src/monitoring/transaction_monitor.js
apps/backend-api/src/notifications/notification_service.js
apps/backend-api/src/routes/monitoring.js
apps/data-processing/report_schedule.yaml
apps/data-processing/scripts/export_and_report.py
apps/data-processing/src/schedulers/report_scheduler.py
apps/data-processing/src/utils/email_utils.py

This PR introduces a comprehensive real-time transaction monitoring system that tracks blockchain activities, delivers instant notifications, and integrates with portfolio management. The system is designed to meet institutional-grade compliance and reporting requirements.
* Real-time blockchain transaction monitoring
* Multi-chain support across various networks
* Transaction categorization and labeling
* Suspicious activity detection
* Instant alert delivery via multiple channels
* Customizable alert thresholds
* User-defined notification preferences and filtering
* Escalation procedures for critical events
* AML/KYC compliance checks
* Regulatory reporting capabilities
* Transaction risk scoring
* Audit trail generation
* Implemented blockchain monitoring using WebSockets for real-time …

Real time transaction monitoring system
